dp14/urls.py
from django.contrib import admin
from django.urls import path,include
import dp14app
from dp14app import views,urls
#import static and settings to connect media url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name="base"),
    path('',views.home,name="home"),
    path('dp14app/',include("dp14app.urls")),
]
if settings.DEBUG==True:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dp14app/urls.py
from django.urls import path
from dp14app import views
app_name="dp14app"

urlpatterns = [
    path('trail/',views.trial,name="Trial"),
    path('profile/',views.profile,name="profile"),
    path('get_demo/',views.get_demo,name="get_demo"),
    path('post_demo/',views.post_demo,name="post_demo"),
    path('register/',views.register,name="register"),
    path('multi/',views.multiplesel,name="multi"),
    path('imgupld/',views.imgupld,name="imgupld"),
]

dp14app/models.py
from django.db import models

# Create your models here.

dp14app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail


def trial(request):
    return HttpResponse("<h1>Project is on air</h1>")

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"dp14app/home.html")

def profile(request):
    name="akshay"
    return render(request,"dp14app/profile.html",{'name':name})

def get_demo(request):
    name=request.GET.get('name')
    return render(request,"get_demo.html",{'name':name})


def post_demo(request):
    if request.method=="POST":
        name=request.POST.get('name')
        return HttpResponse("<h1>Thanks for submission Mr./Ms. {}</h1>".format(name))
    return render(request,"post_demo.html")

def register(request):
    if request.method=="POST":
        first_name=request.POST.get("first_name")
        last_name=request.POST.get("last_name")
        email=request.POST.get("email")
        phoneno=request.POST.get("phone_no")
        pwd=request.POST.get("pwd")
        date=request.POST.get("birthday_day")
        month=request.POST.get("birthday_month")
        year=request.POST.get("birthday_year")
        gender=request.POST.get("sex")
        if gender=='1':
            gender="Female"
        else:
            gender="Male"
        send_mail("Thank you for registration", "mr/ms.{} {}\n Thanks for registerinng with us".format(first_name,last_name),"abhidenim10@gmail.com",[email,],fail_silently=False)
        return HttpResponse("{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>".format(first_name,last_name,email,phoneno,date,month,year,gender))
    return render(request,"dp14app/register.html")

from django.core.files.storage import FileSystemStorage
def multiplesel(request):
    if request.method=="POST":
        foods=request.POST.getlist("food")
        languages=request.POST.getlist("language")
        return HttpResponse("<h1>{}{}</h1>".format(foods,languages))
    return render(request,"multisel.html")

def imgupld(request):
    if request.method=="POST" and request.FILES:
        image=request.FILES['immg']
        fs=FileSystemStorage()
        fs.save(image.name,image)
    return render(request,"img_upld.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>base.html</title>
    {% endblock %}
   <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>-->
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% include "partials/_topbar.html" %}
    {% include "partials/_navbar.html" %}
    {% block content %}
    <div class="container">
        <div class="jumbotron">
            <pre>welcome to &nbsp;&nbsp;&nbsp;<text>base page</text></pre>
            <img src="{% static 'images/django.png' %}" height="50" width="100" alt="No image found">
        </div>
    </div>
    {% endblock %}
    {% include "partials/_footbar.html" %}
</body>
</html>

templates/dp14app/home.html
{% extends "base.html" %}

{% block title %}
<title>home.html</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <pre>welcome to &nbsp;&nbsp;&nbsp; <text>home page</text></pre>
    </div>
</div>
{% endblock %}

templates/dp14app/profile.html
{% extends "base.html" %}

{% block title %}
<title>profile.html</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <pre>Welcome to &nbsp;&nbsp; <text>profile page {{name}}</text></pre>
    </div>
</div>
{% endblock %}

templates/get_demo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GET Demo</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% include 'partials/_topbar.html' %}
    <div class="container">
        <div class="jumbotron">
            <form method="GET" align="center">
                <label for="name">Name:</label>
                <input type="text" name="name" id="name">
                <input type="submit" value="submit">
            </form>
            <pre align="center">{{name}}</pre>
        </div>
    </div>
    {% include 'partials/_footbar.html' %}
</body>
</html>

templates/img_upld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image upload</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data" align="center">
        {% csrf_token %}
    Image:<input type="file" name="immg" value="img">
    <input type="submit" value="submit">
    </form>   
</body>
</html>

templates/multisel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Multi select & Checkboxes</title>
</head>
<body>
    <form method="POST" align="center">
        {% csrf_token %}
        <label for="languages">Choose your language:</label>
        <select name="language" id="languages" multiple>
            <option value="python">Python</option>
            <option value="java">Java</option>
            <option value="c#">C#</option>
            <option value="c++">C++</option>
            <option value="c">C</option>
        </select><br>
        <label for="idli">
            Idli
        </label>
        <input type="checkbox" name="food" id="idli" value="IDLI">
        <label for="dosa">
            Dosa
        </label>
        <input type="checkbox" name="food" id="dosa" value="DOSA">
        <label for="upma">
            upma
        </label>
        <input type="checkbox" name="food" id="upma" value="UPMA">
        <label for="vada">
            vada
        </label>
        <input type="checkbox" name="food" id="vada" value="VADA"><br>
        <input type="submit" value="submit">
    </form>
</body>
</html>

templates/partials/_footbar.html
<div class="alert alert-primary" role="alert">
    <center>footer</center> 
</div>

templates/partials/_navbar.html
<div class="container">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dp14app:profile' %}">profile</a>
      </li>
    </ul>
</div>

templates/partials/_topbar.html
<div class="alert alert-secondary" role="alert">
    <center>Top Bar</center> 
</div>

templates/post_demo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>POST demo</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% include 'partials/_topbar.html' %}
    <div class="container">
        <div class="jumbotron">
            <form method="POST" align="center">
                {% csrf_token %}
                <label for="name">Name:</label>
                <input type="text" name="name" id="name">
                <input type="submit" value="submit">
            </form>
        </div>
    </div>
    {% include 'partials/_footbar.html' %}
</body>
</html>